import { useState } from 'react'
import { ConnectionDetailsPanel } from '../components/ConnectionDetailsPanel'
import type { ConnectionSummary, DeploymentPlan } from '../types'

export function ConnectPage({ plan, connections, notice, onBoxConnection, onSalesforceConnection, onBack, onNext }: { plan: DeploymentPlan; connections: ConnectionSummary[]; notice: string; onBoxConnection: () => void; onSalesforceConnection: () => void; onBack: () => void; onNext: () => void }) {
  const [selectedID, setSelectedID] = useState(plan.components[0]?.id ?? 'box')
  const selected = plan.components.find((component) => component.id === selectedID) ?? plan.components[0]
  const selectedConnection = connections.find((connection) => connection.name.toLowerCase() === selected?.id)
  const openConnection = (id: string) => { if (id === 'box') onBoxConnection(); else onSalesforceConnection() }
  return <section className="connect-stage" aria-label="Connect systems"><header className="task-heading"><div><h2>Connect systems</h2><p>Select a system to inspect its connection details, then connect or reconnect it when needed.</p></div></header><box-split-view className="connect-workspace" label="System connections and selected connection details" ratio={0.64}><div slot="primary" className="connection-list">{plan.components.map((component) => <box-card className={`connection-card ${component.ready ? 'connection-ready' : 'connection-attention'} ${component.id === selectedID ? 'selected' : ''}`} key={component.id}><article className="connection-row" role="button" tabIndex={0} aria-pressed={component.id === selectedID} onClick={() => setSelectedID(component.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedID(component.id) } }}><span className="connection-state" aria-hidden="true">{component.ready ? '✓' : '!'}</span><div><h3>{component.name}</h3><p>{component.ready ? 'Connection verified and ready for validation.' : component.configured ? 'Connection saved; it needs verification.' : 'Connection has not been configured.'}</p></div><div className="connection-action"><strong>{component.ready ? 'Connected' : 'Action needed'}</strong><box-button label={component.ready ? 'Reconnect' : 'Connect'} tone="secondary" onClick={(event) => { event.stopPropagation(); openConnection(component.id) }}></box-button></div></article></box-card>)}</div>{selected && <ConnectionDetailsPanel component={selected} connection={selectedConnection} onEdit={() => openConnection(selected.id)}/>}</box-split-view><footer className="connect-footnote"><p className="notice" role="status">{notice}</p><div className="connect-actions"><span>Dispatch rechecks connections only when you choose a different system or connection.</span><div className="stage-navigation"><box-button label="Back" tone="secondary" onClick={onBack}></box-button><box-button label="Next" tone="primary" onClick={onNext}></box-button></div></div></footer></section>
}
