import { DetailList, DetailsRail } from '../components/DetailsRail'
import type { DeploymentPlan } from '../types'

export function ReviewPage({ plan, notice, onDeploy, onEditConnections, onBack }: { plan: DeploymentPlan; notice: string; onDeploy: () => void; onEditConnections: () => void; onBack: () => void }) {
  const status = plan.components.every((component) => component.ready) ? 'Ready' : 'Needs attention'
  const ready = status === 'Ready'
  return <section className="review-layout review-layout-single" aria-label="Review deployment plan"><article className="task-surface review-surface"><header className="task-heading"><div><h2>{ready ? 'Ready to validate' : 'Connection needs attention'}</h2><p>{ready ? 'Dispatch will check this plan before it applies any change.' : 'Choose a verified connection before starting validation.'}</p></div><span className={`status ${ready ? 'ready' : 'running'}`}>{status}</span></header><div className="review-summary"><div><span>Solution</span><strong>{plan.template}</strong></div><div><span>Strategy</span><strong>{plan.strategy === 'reuse' ? 'Reuse existing' : 'Create new'}</strong></div><div><span>Providers</span><strong>{plan.components.map((component) => component.name).join(' + ')}</strong></div></div><div className="review-details"><PlanGroup title="Package" rows={[["Source", plan.repository]]}/>{plan.components.map((component) => <PlanGroup key={component.id} title={component.name} rows={[["Connection", component.ready ? 'Verified and ready' : component.configured ? 'Configured — needs verification' : 'Not configured']]}/>)}</div><p className="notice" role="status">{notice}</p><footer className="action-row"><div className="stage-navigation"><box-button label="Back" tone="secondary" onClick={onBack}></box-button><box-button label="Start validation" tone="primary" onClick={onDeploy}></box-button></div></footer></article><DetailsRail title="Deployment details" description="Review the saved choices before validation begins."><DetailList rows={[["Strategy", plan.strategy === 'reuse' ? 'Reuse existing' : 'Create new'], ['Systems', plan.components.map((component) => component.name).join(', ')], ['Connection status', ready ? 'Verified' : 'Needs attention']]}/><box-button label="Edit connections" tone="secondary" onClick={onEditConnections}></box-button></DetailsRail></section>
}

function PlanGroup({ title, rows }: { title: string; rows: [string, string][] }) {
  return <section className="plan-group"><h3>{title}</h3>{rows.map(([label, value]) => <div className="plan-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
}
